// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.71.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

abstract class Native {
  Future<AWSProfile> getAwsCredential(
      {required AWSProfile profile, String? mfaCode, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetAwsCredentialConstMeta;

  Future<List<S3Bucket>> s3ListBuckets(
      {required AWSProfile profile, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kS3ListBucketsConstMeta;

  Future<List<S3Object>> s3ListObjects(
      {required AWSProfile profile,
      required S3Bucket bucket,
      String? prefix,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kS3ListObjectsConstMeta;

  Future<bool> s3CreateFolder(
      {required AWSProfile profile,
      required String bucketName,
      required String prefix,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kS3CreateFolderConstMeta;

  Future<bool> s3UploadFile(
      {required AWSProfile profile,
      required String bucketName,
      String? prefix,
      required String filePath,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kS3UploadFileConstMeta;

  Future<bool> s3DeleteObjects(
      {required AWSProfile profile,
      required String bucketName,
      required List<String> prefixes,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kS3DeleteObjectsConstMeta;

  Future<List<String>> s3GetObjects(
      {required AWSProfile profile,
      required String bucketName,
      required List<String> prefixes,
      required S3GetObjectConfig config,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kS3GetObjectsConstMeta;
}

class AWSProfile {
  final String name;
  final String region;
  final String accessKeyId;
  final String secretAccessKey;
  final String? sessionToken;
  final String? mfaSerial;
  final String? expiration;

  const AWSProfile({
    required this.name,
    required this.region,
    required this.accessKeyId,
    required this.secretAccessKey,
    this.sessionToken,
    this.mfaSerial,
    this.expiration,
  });
}

class S3Bucket {
  final String name;
  final String? createdAt;
  final String location;

  const S3Bucket({
    required this.name,
    this.createdAt,
    required this.location,
  });
}

class S3GetObjectConfig {
  final String? saveDir;
  final bool zipForFolder;

  const S3GetObjectConfig({
    this.saveDir,
    required this.zipForFolder,
  });
}

class S3Object {
  final String key;
  final String? lastModified;
  final int? size;
  final String? storageClass;
  final bool isFolder;

  const S3Object({
    required this.key,
    this.lastModified,
    this.size,
    this.storageClass,
    required this.isFolder,
  });
}
